# Generated by Django 6.0.5 on 2026-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
