# Generated by Django 6.0.5 on 2026-07-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='service',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
