# Generated by Django 6.0.5 on 2026-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('result_one', models.CharField(max_length=30)),
                ('result_one_title', models.CharField(max_length=50)),
                ('result_two', models.CharField(max_length=30)),
                ('result_two_title', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
